# Generated by Django 4.2.6 on 2023-10-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_status', models.CharField(choices=[('owned', 'صاحب'), ('mortgage', 'رهن')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('dependents', models.CharField(max_length=16)),
                ('income', models.CharField(max_length=16)),
                ('marital_status', models.CharField(choices=[('married', 'متاهل'), ('Single', 'مجرد')], max_length=8)),
                ('risk_questions', models.CharField(max_length=1)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='InsuranceAPI.housemodel')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='InsuranceAPI.vehiclemodel')),
            ],
        ),
    ]
